GET http://localhost:8080/api/anuncio/2/pecas

###

GET http://localhost:8080/api/anuncio/1/volante

###
POST http://localhost:8080/api/anuncio
Content-Type: application/json

{
    "preco": "100",
    "descricao": "teste do post anuncio",
    "usuario": 2,
    "imagens": [{"src": "img1"}, {"src": "img2"}, {"src": "img3"}],
    "pecas":{
        "carro": "1",
        "pecas": [
            {"tipo": "volante", "estado": "novo"}, 
            {"tipo": "banco", "estado": "usado"}
        ]
    }
}

###
PUT http://localhost:8080/api/anuncio/43
Content-Type: application/json

{
    "preco": "100",
    "data": "2021-03-22",
    "descricao": "teste do post anuncio",
    "estado": "vendido",
    "usuario": 2,
    "imagens": [{"src": "img1"}, {"src": "img2"}, {"src": "img3"}],
    "pecas":{
        "carro": "1",
        "pecas": [
            {"tipo": "volante", "estado": "novo"}, 
            {"tipo": "banco", "estado": "usado"}
        ]
    }
}

###

DELETE http://localhost:8080/api/anuncio/43