# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Subindo o container do mysql
      run: docker run -d -p 3306:3306 --name mysql-teste -v "./db:/scriptDB" -e MYSQL_ROOT_PASSWORD=123 mysql:8.0.23
      run: docker exec -it mysql-teste /bin/bash -c 'mysql -uroot -p123 < scriptDB/userCreation.sql'
    - name: Criando o Banco e Populando
      run: docker exec -it mysql-teste /bin/bash -c 'mysql -uroot -p123 < scriptDB/createDB.sql'
      run: docker exec -it mysql-teste /bin/bash -c 'mysql -uroot -p123 < scriptDB/populate.sql'
    - name: Executand os teste
      run: ./gradlew test
