# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    mysql-teste:
      postgres:
        image: mysql:8.0.23
        env:
          MYSQL_ROOT_PASSWORD: 123
        ports:
          - 3306:3306
        volumes:
       - $(pwd)/db:/scriptDB
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Subindo o container do mysql, criando o banco, populando e testando
      run: |
        docker exec mysql-teste /bin/bash -c 'mysql -uroot -p123 < scriptDB/userCreation.sql'
        docker exec mysql-teste /bin/bash -c 'mysql -uroot -p123 < scriptDB/createDB.sql'
        docker exec mysql-teste /bin/bash -c 'mysql -uroot -p123 < scriptDB/populate.sql'
        ./gradlew test
