# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Teste
    runs-on: ubuntu-latest
    services:
      mysql-teste:
        image: mysql:8.0.23
        env:
          MYSQL_ROOT_PASSWORD: 123
        ports:
          - 3306:3306
        options: --name mysql-teste --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Criando o banco, populando e testando
      run: |
        docker cp $(pwd)/db/userCreation.sql mysql-teste:/s1.sql
        docker exec mysql-teste /bin/bash -c 'mysql -uroot -p123 < s1.sql'
        docker cp $(pwd)/db/createDB.sql mysql-teste:/s2.sql
        docker exec mysql-teste /bin/bash -c 'mysql -uroot -p123 < s2.sql'
        docker cp $(pwd)/db/populate.sql mysql-teste:/s3.sql
        docker exec mysql-teste /bin/bash -c 'mysql -uroot -p123 < s3.sql'
        
